name: Build and deploy

on: [push, pull_request]

jobs:
  lint:
    name: Lint the codebase
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: github/super-linter@v4.7.2
        env:
          FILTER_REGEX_EXCLUDE: "docs/**"
          ERROR_ON_MISSING_EXEC_BIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML: false
  build_prod:
    name: Build and lint the production version
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build the production version
        run: |
          make build-prod
      - name: Super-Linter (docs)
        uses: github/super-linter@v4.7.2
        env:
          FILTER_REGEX_INCLUDE: "docs/**"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
          # Don't validate minified source
          VALIDATE_CSS: false
          VALIDATE_EDITORCONFIG: false
